export interface Order {
  _id?: string;
  OrderTitle: string;
  OrderID?: number; // Auto-generated by backend
  Status?: "Confirmed" | "Pending Admin Review" | "Completed" | "Rejected By Admin" | "User Review Requested" | "Awaiting User Revision" | "Sent To Scholar" | "In Progress By Scholar" | "Revision Requested By Admin" | "Approved By Admin" | "Delivered To User" | "Cancelled" | "Scholar Submitted – Pending Review";
  UserID: string;
  ScholarID: string; // Required by backend
  OrderAmt: number;
  PaymentStatus?: "Unpaid" | "Paid" | "Refunded" | "Pending";
  name: string; // Required by backend
  motherName?: string;
  gender: string; // Required by backend
  phone: string; // Required by backend (not phoneNumber)
  Sect: string; // Required by backend
  Reason: string; // Required by backend
  PrefferedLanguage?: string;
  message?: string;
  AudioURL?: string; // Backend expects AudioURL (capital URL), not audioUrl
  createdAt?: string;
  updatedAt?: string;
  isReadByUser?: boolean;
  selectWazifa?: string;
}